#!/usr/bin/env sh

PRETTIER="./node_modules/.bin/prettier"

if ! "$PRETTIER" --check . --log-level warn; then
  "$PRETTIER" --write . --log-level warn
  echo ""
  echo "Files were reformatted by Prettier. Please commit the changes and push again."
  exit 1
fi
