#!/usr/bin/env sh

if ! yarn prettier --check . --log-level warn; then
  yarn prettier --write . --log-level warn
  echo ""
  echo "Files were reformatted by Prettier. Please commit the changes and push again."
  exit 1
fi
